### Install Required Packages

In [1]:
! pip install numpy pandas scikit-learn matplotlib

### Imports

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Create matrices

In [3]:
# create a matrix with random values
np.random.seed(1)

X = np.random.randint(-50, 50, size=(3, 4))
Y = np.random.randint(-50, 50, size=(4, 3))
g = np.random.randint(-50, 50, size=(4,))
z = np.random.randint(-50, 50, size=(4,))

print(f'X={X} \n\n Y={Y} \n\n g={g} \n\n z={z}')

X=[[-13 -38  22 -41]
 [ 25 -45  29  14]
 [-34 -49  26  21]] 

 Y=[[-44 -25   0]
 [-30 -32  34]
 [-39 -22 -21]
 [-36   0  18]] 

 g=[37 37 44 46] 

 z=[ 36 -37 -41 -43]


### Computations

In [4]:
# Inner product of g and z
inner_prod_g_z = np.inner(g, z)
print(f'Inner product of g and z: \n{inner_prod_g_z} \n')

# Inner product of g and g<Transpose>z
g_transpose = np.array([g]).T
# print(g_transpose)

gTz = np.multiply(g_transpose, z)
# print(gTz)

inner_prod_g_gTz = np.inner(g, gTz)
print(f'Inner product of g and g<Transpose>z :\n{inner_prod_g_gTz} \n')

# Matrix-vector product Xg
vector_prod = np.matmul(X, g)
print(f'Matrix-vector product Xg: \n{vector_prod} \n')

# Dot product XY
dot_prod = np.dot(X, Y)
print(f'Dot product XY: \n{dot_prod} \n')

# L2/Frobenius norms of the vectors and matrices.
X_norm = np.linalg.norm(X)
Y_norm = np.linalg.norm(Y)
g_norm = np.linalg.norm(g)
z_norm = np.linalg.norm(z)

print(f'Norm X: {X_norm}\nNorm Y: {Y_norm}\nNorm g: {g_norm}\nNorm z: {z_norm}\n')

Inner product of g and z: 
-3819 

Inner product of g and g<Transpose>z :
[-141303 -141303 -168036 -175674] 

Matrix-vector product Xg: 
[-2805  1180  -961] 

Dot product XY: 
[[ 2330  1057 -2492]
 [-1385   177 -1887]
 [ 1196  1846 -1834]] 

Norm X: 110.17713011328621
Norm Y: 98.52410872471773
Norm g: 82.40145629781065
Norm z: 78.70832230456955

